#!/bin/bash
## usage: ./run.sh runNumber thread 
# run like:
# ./add  RunNumber NumberOfThread
cd $1
echo "Input the thread you want used, suggestied less than 12!!!"
for (( i=0; i<$2; i++ ))
do
    echo "begin add rootfiles"
    cd $i
    echo $i
    hadd -a ../../fit_csi_$1.root fit_csi_$1.root
    cd ../
done


